// <auto-generated />
using APINodeMcu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APINodeMcu.Migrations
{
    [DbContext(typeof(NodeContext))]
    partial class NodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("APINodeMcu.Models.Dataesp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("dispValor")
                        .HasColumnType("int");

                    b.Property<string>("freqValor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("oxiValor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tempValor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataEsp");
                });
#pragma warning restore 612, 618
        }
    }
}
